version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:7-browsers  
    steps:
      - checkout
      
      - run: node --version
      - run: npm --version
      - run: java -version
      - run: google-chrome --version
      - run: yarn --version

      - run: yarn install
      - run: yarn run format-enforce
      - run: yarn run lint
      
      # Individual tests
      - run: xvfb-run -a yarn run e2e protractor-first-test.conf.js
      - run: xvfb-run -a yarn run e2e protractor-add-contact.conf.js
      - run: xvfb-run -a yarn run e2e protractor-invalid-contact.conf.js
      - run: xvfb-run -a yarn run e2e protractor-contact-list.conf.js
      - run: xvfb-run -a yarn run e2e protractor-page-objects.conf.js
      - run: xvfb-run -a yarn run e2e protractor-tables.conf.js

      # Run all tests
      - run: xvfb-run -a yarn run e2e protractor.conf.js
